### ISSUE TITLE
Prikaz Odgovora u klasi Pitanje

### ISSUE THREAD

**Issue by Miksiandonovic** [Miksiandonovic/kviz#10]
Ovde ćemo diskutovati o mogućim interpretacijama ovog problema. 
**_Problem je sledeći:_**
-Potrebno je naći rešenje za to kako da prikazujemo pitanje, odnosno preciznije odgovore u njemu. Naime naša funkcija Prikazi za sada uvek stavlja tacan odgovor na prvo mesto što je nerealno, tako da je potrebno osmisliti neki novi mehanizam. U komentarima pišite vaše ideje.

**Comment by Markeza1312** [comment]
Ipak sam osmislio novo resenje. Od tacnog odgovora i tri netacna odgovora pravimo 4 promenljive od kojih pravimo listu. Pod indeksom 0 je uvek tacan odgovor, a 1,2,3 su netacni. Nakon toga pravimo rendomizovanu listu tih indeksa koja ce se svaki put menjati pri prikazu novog pitanja. Kada budemo dodeljivali prvom "polju", drugom, trecem i cetvrtom onda cemo samo redom iz te rendomizovane liste dodeljivati brojeve, a posto je pod nultim indeksom iz one prve liste tacan odgovor, najjednostavnijom proverom da li je indeks nula cemo znati da li je to tacan odgovor i pritom sa ovom rendomizovanom listom smo izbegli ponavaljanje istih netacnih odgovora ili tacnog odgovora.

**Comment by n-ratinac** [comment]
Nisam najbolje razumeo. Da li hoces da kazes da mi umesto da mesamo listr stringova, mi mesamo samo listu {0,1,2,3} u npr. {3,0,2,1} koja predstavlja redosled prikazivanja ponudjenih odgovora?

**Comment by Markeza1312** [comment]
Da

**Comment by n-ratinac** [comment]
Nista onda, checkout-u granu kod tebe u lokalu. I, zamolio bih te ako mozes da cesce commitujes. Srecan rad!

**Comment by Markeza1312** [comment]
Vazi

**Comment by Miksiandonovic** [comment]
Marko je zavrsio ovu klasu i commitovao. Datum: 12/18/2024
