### ISSUE TITLE
Odgovornosti

### ISSUE THREAD

**Issue by Miksiandonovic** [Miksiandonovic/kviz#2]
**1. Kreiranje, menjanje i brisanje pitanja:**

-Klasa Pitanje;

-Klasa StorageManager

-Klasa banka Pitanja
--Izbrisi  i Dodaj

-Klasa Kviz

-Klasa Korisnik

**Comment by sogrikraljina007** [comment]
HVALA MIKI IDEMO JAKO

чет, 5. дец 2024. у 19:12 Miksiandonovic ***@***.***> је
написао/ла:

**Comment by Miksiandonovic** [comment]
Svi znaju svoje odgovornosti stoga nije potreban ovaj issue.

**Comment by sogrikraljina007** [comment]
( p1= \sigma_{managerid!=null \wedge min(salary)>1200}(EMPLOYEES) p2= p1 >
departmentid < DEPARTMENTS p3= p2 > locationid < LOCATION p4=p3 > countryid
< COUNTRIES P5= \pi_{lastname,countryname}(p4) \)
