### ISSUE TITLE
Klasa Pitanja 

### ISSUE THREAD

**Issue by Miksiandonovic** [Miksiandonovic/kviz#3]
**Svojstva:**
string tekstPitanja
lista stringa odgovora
indeks tacnog odgovora
int broj bodova
**Getteri i setteri**
Public get, Private set
**Konstruktori**
defaultni konstruktor koji inicijalizuje praznu listu stringa.
parametrizovani koji settuje sve vrednosti
**Metode**
Override metoda prikaziPitanje koja prikazuje formatirano pitanje sa tekstom pitanja, ponudjenim odgovorima i poenima

**Comment by n-ratinac** [comment]
@Miksiandonovic, moras malo detaljnije da definises zahteve, niste mnogo unapred isplanirali.
Ono sto je bitno jeste da ova klasa ima definisane funkcionalnosti i to:
 - cuvanje osnovnih informacija vezanih za pojedinacno pitanje
 - prikaz pitanja kada je kviz u toku
 - pretvaranje pitanja u njenu string reperezentaciju u cilju cuvanja na disk

# Ko i kako koristi ovu klasu?

Ja bih rekao da **Kviz** klasa koristi klasu pitanje da bi ga postavila, da bi proverila da li je korisnik dao tacan odgovor i da zna koliko poena treba da dodeli korisniku.
Takodje, koja god klasa vrsi citanje pitanja sa skladista, mora da moze da konstruise objekat klase Pitanje na osnovu string reprezentacije. Dakle mozda je korisno da imamo konstruktor koji prihvata string reprezentaciju pitanja?

# Definicija zahteva

## Svojstva
- string TekstPitanja
- string TacanOdgovor
- List<string> NetacniOdgovori
- int BrojBodova
- int ID (sluzi za jedinstvenu identifikaciju)

## Metode
- string Prikaz() koja vraca string koji predstavlja kako ce biti pitanje postavljeno korisniku. Npr: 
```
<tekst pitanja> | <broj bodova>
1. <odgovor 1>
2. <odgovor 2>
3. <odgovor 3>
4. <odgovor 4>
```
Neka za sad se tacan odgovor uvek ispisuje na poziciji 1. To cemo menjati kasnije.
- override-ovana ToString() metoda koja vraca string reprezentaciju oblika:
```
ID,TekstPitanja,TacanOdgovor,Netacan1,Netacan2,Netacan3,BrojBodova
```

## Konstruktori

Ovde imamo 2 koji se koriste u 2 razlicita slucaja. 
1. Prvi koji se koristi onda kada se zapravo kreira novo pitanje. Potrebno je da od parametara prima sva svojstva osim ID jer ID mora sam da generise tako da se ne poklapa ni sa jednim drugim pitanjem u bazi pitanja. (Ovo moramo da razmislimo kako da realizujemo maksimalno elegantno)
2. Drugi koji se koristi prilikom citanja baze pitanja sa diska. Najbolje bi bilo da parametar bude samo jedan string koji predstavlja string reprezentaciju pitanja i ulog konstruktora je samo da izvuce vrednosti parametara iz string reprezentacij i setuje atribute

**Comment by n-ratinac** [comment]
@Markeza1312 javi se ovde kad vidis ovo, ako ima nejasnoca, mozemo da pojasnimo

**Comment by Markeza1312** [comment]
> @Markeza1312 javi se ovde kad vidis ovo, ako ima nejasnoca, mozemo da pojasnimo

Vazi

**Comment by Markeza1312** [comment]
Posto sam zavrsio vec sad, ja cu da se trudim da nalazim greske i da pomognem Grigoriju ako mu bude trebala pomoc da bi ucestvovao maksimalno i konstantno pri izradi projekta.

**Comment by Markeza1312** [comment]
Takodje imam ideju kako bi mozda mogli da napravimo da tacan odgovor bude na bilo kom mestu.

**Comment by n-ratinac** [comment]
@Markeza1312 @Miksiandonovic  Mozda da otvorimo novi issue da se pozabavimo ovim?

**Comment by Miksiandonovic** [comment]
Otvaram sada novi issue.

**Comment by Miksiandonovic** [comment]
Klasa je za sada zavrsena, osim ako je potrebno ispraviti nesto.
