### ISSUE TITLE
Klasa StorageManager

### ISSUE THREAD

**Issue by Miksiandonovic** [Miksiandonovic/kviz#5]
Naziv: StorageManager
**Svojstva:**
-/
**Ponasanje:**
-List<Pitanje> UcitajPitanjaIzFajla (string filePath):  Ucitava pitanja iz fajla u listu objekata Pitanje
-void SacuvajPitanjaUFajl (string filePath, List<Pitanje>pitanja) - Cuva listu pitanja u fajl koristeci odgovarajuci format iz fajla.

**Comment by n-ratinac** [comment]
Mislim da bi bilo dobro da StorageManager klasa bude staticka. Takodje, StorageManager moze u statickom polju da pamti putanju do fajla koji cuva pitanja. 

## Metode
- staticka metoda UcitajPitanja() vraca objekat tipa BankaPitanja.
- staticka metoda SacuvajPitanja(BankaPitanja) koja prima instancu tipa BankaPitanja i snima sva pitanja na disk na datoj putanji.

Za sada mislim da je ovo dovoljno. Kako budu iskakali problemi, pravicemo nove Issue-e

**Comment by Miksiandonovic** [comment]
@n-ratinac Profesore, zar ne bismo trebali da funkciji UcitajPitanja šaljemo FilePath ?

**Comment by n-ratinac** [comment]
Odlicno pitanje! Dakle moja zamisao jeste, s obzirmo da je StorageManager staticka klasa, koristicemo je svuda u kodu gde treba, tako da FilePath nije parametar nijedne od funkcija, vec staticko string polje na klasi StorageManager kojem cemo dodeliti neku hardkodiranu vrednost npr. "pitanja.txt".

**Comment by Miksiandonovic** [comment]
Klasa StorageManager je zavrsena. Sada mozemo da idemo u testiranje. Dodate su funkcije UcitajPitanja i SacuvajPitanja.
