### ISSUE TITLE
Klasa BankaPitanja

### ISSUE THREAD

**Issue by Miksiandonovic** [Miksiandonovic/kviz#6]
**Svojstva**
-List<Pitanje> Pitanja
**Konstruktor**
-BankaPitanja (string filePath, StorageManager storagemanager) ucitava pitanja iz fajla koristeci storage manager
**Ponasanja**
-List<Pitanje>GenerisiRandomPitanje (int brojPitanja) -vraca n pitanja nasumicno odabranih iz liste.
-void DodajPitanje (pitanje novoPitanje) - dodaje novo pitanje u listu i cuva promene u fajlu
-void ObrisiPitanja (int indeks) brise pitanje na osnovu indeksa i cuva promene u fajlu
-List<Pitanje>SvaPitanja() - vraca listu svih pitanja

**Comment by Miksiandonovic** [comment]
Branch ce biti napravljen po zavrsetku klase StorageManager

**Comment by n-ratinac** [comment]
> **Konstruktor** -BankaPitanja (string filePath, StorageManager storagemanager) ucitava pitanja iz fajla koristeci storage manager 

Mislim da konstruktor treba samo da primi listu pitanja koja je rezultat metode UcitajPitanja() na klasi StorageManager. S obzirom da je StorageManager staticka klasa, onda je dostupna svuda u kodu.
BankaPitanja uopste se ne brine o tome kako ce da se cuva na disk, to je uloga StorageManager klase.
Njena jedina uloga jeste da pruzi metode za manipulaciju pitanjima unutar liste pitanja.

## Metode
- DodajPitanje(Pitanje) koje dato pitanje dodaje na kraj liste pitanja.
- ObrisiPitanje(int ID) koje brise pitanje sa datim ID-em.
- IzlistajPitanja() koja vraca string oblika:
```
ID1,TekstPitanja1
ID2,TekstPitanja2
...
IDN,TekstPitanjaN
```
- NasumicnaPitanja(int n, int m) vraca listu od `n` nasumicnih pitanja tezine `m`

**Comment by Miksiandonovic** [comment]
Profesore, da li bi funkcija IzlistajPitanja() tebala da vraca listu stringova?

**Comment by n-ratinac** [comment]
> Profesore, da li bi funkcija IzlistajPitanja() tebala da vraca listu stringova?

Pa ne bas. Treba da vrati string reprezentaciju liste pitanja da bi korisnik znao koliko. Dakle samo jedan string, koji je razdvojen novim redovima za svako pitanje.

**Comment by Miksiandonovic** [comment]
Dogovoreno, sada ću to da ispravim. Uradio sam sve ostale funkcije.

**Comment by n-ratinac** [comment]
Otvori pull request da mozemo da vidimo tacno kako ide.
